services:
  - type: web
    name: snapload-api
    runtime: node
    plan: free
    buildCommand: pip3 install yt-dlp && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        generateValue: true
      - key: YTDLP_BINARY
        value: /home/render/.local/bin/yt-dlp